apiVersion: apps/v1
kind: Deployment
metadata:
  name: forklift-controller
  labels:
    app: forklift-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forklift-controller
  template:
    metadata:
      labels:
        app: forklift-controller
    spec:
      containers:
        - name: forklift-controller
          image: wuhan005/forklift:controller
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
          volumeMounts:
            - name: forklift-configmap
              mountPath: /etc/forklift
      serviceAccountName: forklift-service-account
      automountServiceAccountToken: true
      hostPID: true
      volumes:
        - name: forklift-configmap
          configMap:
            name: forklift-configmap
