apiVersion: v1
kind: Service
metadata:
  name: forklift-controller
  labels:
    app: forklift-controller
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
    selector:
        app: forklift-controller
