apiVersion: v1
kind: ConfigMap
metadata:
  name: forklift-configmap
data:
  forklift.yaml: |
    active-namespaces:
      {{- range $namespace := .Values.controller.activeNamespace }}
      - {{ $namespace }}
      {{- end }}
