apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: forklift-daemonset
  labels:
    app: forklift-daemonset
spec:
    selector:
      matchLabels:
        app: forklift-daemonset
    template:
        metadata:
          labels:
              app: forklift-daemonset
        spec:
          containers:
            - name: forklift-daemonset
              image: {{ .Values.image.daemon }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              securityContext:
                  privileged: true
          serviceAccountName: forklift-service-account
          automountServiceAccountToken: true
          hostPID: true
