apiVersion: apps/v1
kind: Deployment
metadata:
  name: forklift-controller
  labels:
    app: forklift-controller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: forklift-controller
  template:
    metadata:
      labels:
        app: forklift-controller
    spec:
      containers:
        - name: forklift-controller
          image: {{ .Values.image.controller }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: forklift-configmap
              mountPath: /etc/forklift
      serviceAccountName: forklift-service-account
      automountServiceAccountToken: true
      hostPID: true
      volumes:
        - name: forklift-configmap
          configMap:
            name: forklift-configmap
