apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: forklift-role-binding
subjects:
  - kind: ServiceAccount
    name: forklift-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: forklift-role
  apiGroup: rbac.authorization.k8s.io
