apiVersion: v1
entries:
  forklift:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-13T18:41:40.006622+08:00"
    description: Lightweight image pre-download component for Kubernetes.
    digest: 00f39b4993e0c8fd865eb556febe0d9af36a2890236a8d22bdb4111b451e9f61
    name: forklift
    type: application
    urls:
    - charts/forklift-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-13T18:41:40.005379+08:00"
    description: Lightweight image pre-download component for Kubernetes.
    digest: dadfe442acdde23d5e8836fc388f3790bec0fdb43db5276e088aca49bb9097fe
    name: forklift
    type: application
    urls:
    - charts/forklift-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-13T18:41:40.003875+08:00"
    description: Lightweight image pre-download component for Kubernetes.
    digest: 80909b28a39a9f0afd35743ec9909ce63edc63c3d00bdc07655c0d3009014b6a
    name: forklift
    type: application
    urls:
    - charts/forklift-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-13T18:41:40.003437+08:00"
    description: Lightweight image pre-download component for Kubernetes.
    digest: 320e55ddcb74e6565668a42787f7e672d962c0a546a23fc9f78e5ee86a93c31a
    name: forklift
    type: application
    urls:
    - charts/forklift-0.1.0.tgz
    version: 0.1.0
generated: "2023-03-13T18:41:40.002982+08:00"
