name: Release
on:
  push:

jobs:
  push-docker-hub:
    name: Push Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - name: Build
        run: |
          go build -ldflags '-s -w' -v ./cmd/controller -o ./cmd/controller/controller
          docker build ./cmd/controller -t wuhan005/forklift:controller
          
          go build -ldflags '-s -w' -v ./cmd/daemon -o ./cmd/daemon/daemon
          docker build ./cmd/daemon -t wuhan005/forklift:daemon
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: |
          docker push wuhan005/forklift:controller
          docker push wuhan005/forklift:daemon
    
